name: Deploy Lambda Function (Test)

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**/*.yml'
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/src/requirements.txt

    # Setup variables for moto testing
    - name: Set environment variables for mock AWS tests
      run: |
        echo "AWS_ACCESS_KEY_ID=fake-access-key-id"
        echo "AWS_SECRET_ACCESS_KEY=fake-secret-access-key"
        echo "AWS_DEFAULT_REGION=eu-west-2"
        echo "AWS_SESSION_TOKEN=testing"
        echo "AWS_SECURITY_TOKEN=testing"

    # Run Codacy analysis
    - name: Run Codacy Analysis
      uses: codacy/codacy-analysis-cli-action@97bf5df3c09e75f5bcd72695998f96ebd701846e
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        verbose: true
        max-allowed-issues: 2147483647

    # Run pytest
    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=$(pwd)
        pytest
